[DEVICE1]
; Настройки для первого устройства
name = ЮНИТ-М300-ДЗТ2
version = 1.0
path_to_latex_desc = //192.168.11.240/Company/Ivanovo/Документация ЮНИТ М300/Разработка/Схемы ФБ ЮНИТ-М300/Проект/РЭ/01. РЭ ЮНИТ-М3-ДЗТ2
order_code = ЮНИТ-М319-ДЗТ2-Р02с-х-К002-К002-К002-К002-К002-В021-В021-В021-В021-М090.9000-х-С01.00-2.1
full_description = МИКРОПРОЦЕССОРНОЕ УСТРОЙСТВО ЗАЩИТЫ И АВТОМАТИКИ ТРАНСФОРМАТОРА
manual_code = ЮТКБ.656122.609 РЭ6
order_code_hmi = ЮНИТ-ИЧМ-СУГР-С-С
setting_blanc_code = ЮТКБ.656122.609 БУ6
versions = [{"edition": "1.0", "data": "17.07.2025"},{"edition": "1.1", "data": "18.09.2025"},{"edition": "1.2", "data": "11.10.2025"}]
; путь к пдф файла РУ для обновления перечня сокращений
path_to_ru_desc = //192.168.11.240/Company/Ivanovo/Документация ЮНИТ М300/Разработка/Схемы ФБ ЮНИТ-М300/Проект/РУ/01. РЭ ЮНИТ-М3-ДЗТ2/general.pdf


[DEVICE2]
; Настройки для второго устройства
name = ЮНИТ-М300-Т
version = 1.0
path_to_latex_desc = //192.168.11.240/Company/Ivanovo/Документация ЮНИТ М300/Разработка/Схемы ФБ ЮНИТ-М300/Проект/РЭ/02. РЭ ЮНИТ-М3-Т
order_code = ЮНИТ-М319-Т-Р02с-х-К002-К002-К001-В001-В001-В021-В021-В021-В021-М044.abcd-х-С01.a0-2.1
full_description = МИКРОПРОЦЕССОРНОЕ УСТРОЙСТВО ЗАЩИТЫ И АВТОМАТИКИ ТРАНСФОРМАТОРА
manual_code = ЮТКБ.656122.609 РЭ8
order_code_hmi = ЮНИТ-ИЧМ-СУГР-С-С
setting_blanc_code = ЮТКБ.656122.609 БУ8
versions = [{"edition": "1.0", "data": "17.07.2025"},{"edition": "1.1", "data": "18.09.2025"},{"edition": "1.2", "data": "11.10.2025"}]
; путь к пдф файла РУ для обновления перечня сокращений
path_to_ru_desc = //192.168.11.240/Company/Ivanovo/Документация ЮНИТ М300/Разработка/Схемы ФБ ЮНИТ-М300/Проект/РУ/02. РЭ ЮНИТ-М3-Т/general.pdf

[DEVICE3]
; Настройки для третьего устройства
; Почему то для ЗП разные блоки T_AUTOVC и T2_TOVCTOC??? для Т и Т2
; Также ЛО Т у меня одна 35. ЛО Т 35 Т (TOFFLVLGC), у них здесь TRESOFFLVLGC, оставил как в Т
name = ЮНИТ-М300-Т2
version = 1.0
path_to_latex_desc = //192.168.11.240/Company/Ivanovo/Документация ЮНИТ М300/Разработка/Схемы ФБ ЮНИТ-М300/Проект/РЭ/04. РЭ ЮНИТ-М3-Т2
order_code = ЮНИТ-М319-Т2-Р02с-х-К002-К002-К002-В001-В001-В001-В021-В021-В021-М046.abcd-х-С01.a0-2.1
full_description = МИКРОПРОЦЕССОРНОЕ УСТРОЙСТВО ЗАЩИТЫ И АВТОМАТИКИ ТРАНСФОРМАТОРА
manual_code = ЮТКБ.656122.609 РЭ7
order_code_hmi = ЮНИТ-ИЧМ-СУГР-С-С
setting_blanc_code = ЮТКБ.656122.609 БУ7
versions = [{"edition": "1.0", "data": "17.07.2025"},{"edition": "1.1", "data": "18.09.2025"},{"edition": "1.2", "data": "11.10.2025"}]
; путь к пдф файла РУ для обновления перечня сокращений
path_to_ru_desc = //192.168.11.240/Company/Ivanovo/Документация ЮНИТ М300/Разработка/Схемы ФБ ЮНИТ-М300/Проект/РУ/03. РЭ ЮНИТ-М3-Т2/general.pdf

[DEVICE4]
; Настройки для устройства ОЛ
name = ЮНИТ-М300-ОЛ
version = 1.0
path_to_latex_desc = //192.168.11.240/Company/Ivanovo/Документация ЮНИТ М300/Разработка/Схемы ФБ ЮНИТ-М300/Проект/РЭ/05. РЭ ЮНИТ-М3-ОЛ
order_code = ЮНИТ-М319-ОЛ-Р02с-х-К002-К002-К002-К002-К002-В021-В021-В021-В021-М046.3001-х-С01.00-2.1
full_description = МИКРОПРОЦЕССОРНОЕ УСТРОЙСТВО ЗАЩИТЫ И АВТОМАТИКИ ОТХОДЯЩЕЙ ЛИНИИ
manual_code = ЮТКБ.656122.609 РЭ2
order_code_hmi = ЮНИТ-ИЧМ-СУГР-С-С
setting_blanc_code = ЮТКБ.656122.609 БУ2
versions = [{"edition": "1.0", "data": "17.07.2025"},{"edition": "1.1", "data": "05.08.2025"},{"edition": "1.2", "data": "11.10.2025"}]
; путь к пдф файла РУ для обновления перечня сокращений
path_to_ru_desc = 

[DEVICE5]
; Настройки для устройства ТН
name = ЮНИТ-М300-ТН
version = 1.0
path_to_latex_desc = //192.168.11.240/Company/Ivanovo/Документация ЮНИТ М300/Разработка/Схемы ФБ ЮНИТ-М300/Проект/РЭ/06. РЭ ЮНИТ-М3-ТН
order_code = ЮНИТ-М319-ТН-Р02с-х-К001-К001-К001-К001-В021-В021-В001-х-х-М008.0000-х-С01.00-2.1
full_description = МИКРОПРОЦЕССОРНОЕ УСТРОЙСТВО ЗАЩИТЫ И АВТОМАТИКИ ТРАНСФОРМАТОРА НАПРЯЖЕНИЯ
manual_code = ЮТКБ.656122.609 РЭ5
order_code_hmi = ЮНИТ-ИЧМ-СУГР-С-С
setting_blanc_code = ЮТКБ.656122.609 БУ5
versions = [{"edition": "1.0", "data": "17.07.2025"},{"edition": "1.1", "data": "13.08.2025"},{"edition": "1.2", "data": "11.10.2025"}]
; путь к пдф файла РУ для обновления перечня сокращений
path_to_ru_desc = 

[DEVICE6]
; Настройки для устройства ВВ
name = ЮНИТ-М300-ВВ
version = 1.0
path_to_latex_desc = //192.168.11.240/Company/Ivanovo/Документация ЮНИТ М300/Разработка/Схемы ФБ ЮНИТ-М300/Проект/РЭ/07. РЭ ЮНИТ-М3-ВВ
order_code = ЮНИТ-М319-ВВ-Р02с-х-К002-К002-К002-К002-К002-В021-В021-В021-В021-М037.3000-х-С01.00-2.1
full_description = МИКРОПРОЦЕССОРНОЕ УСТРОЙСТВО ЗАЩИТЫ И АВТОМАТИКИ ВВОДНОГО ВЫКЛЮЧАТЕЛЯ
manual_code = ЮТКБ.656122.609 РЭ3
order_code_hmi = ЮНИТ-ИЧМ-СУГР-С-С
setting_blanc_code = ЮТКБ.656122.609 БУ3
versions = [{"edition": "1.0", "data": "17.07.2025"},{"edition": "1.1", "data": "11.08.2025"},{"edition": "1.2", "data": "11.10.2025"}]
; путь к пдф файла РУ для обновления перечня сокращений
path_to_ru_desc = 

[DEVICE7]
; Настройки для устройства СВ
name = ЮНИТ-М300-СВ
version = 1.0
path_to_latex_desc = //192.168.11.240/Company/Ivanovo/Документация ЮНИТ М300/Разработка/Схемы ФБ ЮНИТ-М300/Проект/РЭ/08. РЭ ЮНИТ-М3-СВ
order_code = ЮНИТ-М319-СВ-Р02с-х-К002-К002-К002-К002-К002-В021-В021-В021-В021-М037.3000-х-С01.00-2.1
full_description = МИКРОПРОЦЕССОРНОЕ УСТРОЙСТВО ЗАЩИТЫ И АВТОМАТИКИ СЕКЦИОННОГО ВЫКЛЮЧАТЕЛЯ
manual_code = ЮТКБ.656122.609 РЭ4
order_code_hmi = ЮНИТ-ИЧМ-СУГР-С-С
setting_blanc_code = ЮТКБ.656122.609 БУ4
versions = [{"edition": "1.0", "data": "17.07.2025"},{"edition": "1.1", "data": "12.08.2025"},{"edition": "1.2", "data": "11.10.2025"}]
; путь к пдф файла РУ для обновления перечня сокращений
path_to_ru_desc = 

[DEVICE8]
; Настройки для устройства АРНТ
name = ЮНИТ-М300-АРНТ
version = 1.0
path_to_latex_desc = //192.168.11.240/Company/Ivanovo/Документация ЮНИТ М300/Разработка/Схемы ФБ ЮНИТ-М300/Проект/РЭ/09. РЭ ЮНИТ-М3-АРНТ
order_code = ЮНИТ-М314-АРНТ-Р02с-х-К002-К001-В021-В021-А004-М046.4000-х-С01.00-2.1
full_description = МИКРОПРОЦЕССОРНОЕ УСТРОЙСТВО АВТОМАТИЧЕСКОГО РЕГУЛИРОВАНИЯ НАПРЯЖЕНИЯ
manual_code = ЮТКБ.656122.609 РЭ9
order_code_hmi = ЮНИТ-ИЧМ-КУГР
setting_blanc_code = ЮТКБ.656122.609 БУ9
versions = [{"edition": "1.0", "data": "17.07.2025"},{"edition": "1.1", "data": "12.08.2025"},{"edition": "1.2", "data": "11.10.2025"}]
; путь к пдф файла РУ для обновления перечня сокращений
path_to_ru_desc = 

[DEVICE9]
; Настройки для устройства ВСЕ ТЕСТОВОЕ
name = ЮНИТ-М300-ТЕСТ
version = 1.0
path_to_latex_desc = //192.168.11.240/Company/Ivanovo/Документация ЮНИТ М300/Разработка/Схемы ФБ ЮНИТ-М300/Проект/РЭ/09. РЭ ЮНИТ-М3-АРНТ
order_code = ЮНИТ-М314-ВСЕ-Р02с-К002-К001-А004-В021-В021-В001-М046.4000-х-С01.00-2.1
full_description = МИКРОПРОЦЕССОРНОЕ УСТРОЙСТВО ТЕСТОВОЕ
manual_code = ЮТКБ.656122.609 РЭ9
order_code_hmi = ЮНИТ-ИЧМ-СУГР-С-К-С-К
setting_blanc_code = ЮТКБ.656122.609 БУ9
versions = [{"edition": "1.0", "data": "17.07.2025"},{"edition": "1.1", "data": "12.08.2025"},{"edition": "1.2", "data": "11.10.2025"}]
; путь к пдф файла РУ для обновления перечня сокращений
path_to_ru_desc = 